### ISSUE TITLE
sel4-kernel-loader drops ELF debug sections

### ISSUE THREAD

**Issue by BDUG** [seL4/rust-sel4#179]
Due to conversation at [here](https://github.com/seL4/seL4/issues/1313) I would like to raise an bug. 

 After the call of `sel4-kernel-loader` in correlation with `sel4-kernel-loader-add-payload` the resulting ELF-file no longer contains respective debug sections. Is there any option to keep the sections?

**Comment by nspin** [comment]
The output of `sel4-kernel-loader-add-payload` is only meant to be consumed by bootloaders, not debuggers. The original `sel4-kernel-loader.elf`, which is used as input to `sel4-kernel-loader-add-payload`, can be used for debugging.

### Why

The `sel4-kernel-loader` program, like the similar and more prevalent [`elfloader` program](https://github.com/seL4/seL4_tools/tree/master/elfloader-tool), isn't a full-fledged bootloader. It encapsulates only the seL4-specific aspects of booting seL4. It is designed to be called by a bootloader that handles all of the more generic aspects of booting.

In the name of simplicity and minimalism, we don't want `sel4-kernel-loader` to have to look very hard to find the kernel and root task images. Specifically, we want the `sel4-kernel-loader` program image that is supplied to the bootloader to contain both the `sel4-kernel-loader` program and the data it requires to load the kernel and root tasks.

The `sel4-kernel-loader-add-payload` tool takes a generic `sel4-kernel-loader.elf` (compiled separately from the kernel and root task), `kernel.elf`, and a root task ELF file, and creates a new program image based on `sel4-kernel-loader.elf`, but with the data required for loading the kernel and root task. For the sake of keeping the `sel4-kernel-loader-add-payload` tool simple, this final program image is an ELF file with only program headers, and no section headers (and thus no symbols or debugging information). However, the debugging information in the original `sel4-kernel-loader.elf` passed to `sel4-kernel-loader-add-payload` still applies to the final program image.

I have deemed this approach to be the most streamlined from both an implementation standpoint and from the perspective of downstream build systems. The only drawback that I can think of is this non-intuitive fact that the original `sel4-kernel-loader.elf` is the one that is to be used for debugging.
