### ISSUE TITLE
What version(s) of seL4 does this project support?

### ISSUE THREAD

**Issue by Gallium70** [seL4/rust-sel4#40]
I would like to write some seL4 driver and app in rust. I briefly checked the doc and code of this project, but didn't find instruction about seL4 versions. Does it support latest release (v12.1.0), bleeding edge (master), or is compatible with multiple versions?

Previously I was trying with [Robigalia devbox](https://gitlab.com/robigalia/devbox), however there's not much active development ever since seL4 v12.0.0 release. Per my understanding, they try to generate rust bindings automatically by parsing libsel4 C-headers and xml files, whose formats are not so stable across different seL4 versions, causing the parser and generator ([sel4-idlgen](https://gitlab.com/robigalia/sel4-idlgen)) broken on newer version.

**Comment by nspin** [comment]
Thanks for pointing out this gap in the documentation.

I've added this information in https://github.com/seL4/rust-sel4/pull/44.

It can be found here: https://github.com/seL4/rust-sel4#compatible-versions-of-related-sel4-foundation-projects.

The upcoming release of seL4 will be the first release supported by this project. Same for the seL4 Microkit. So, for now, the compatible "versions" are just commit hashes.
