### ISSUE TITLE
Is there a crate here that can quickly create new threads? 

### ISSUE THREAD

**Issue by CtrlZ233** [seL4/rust-sel4#98]
When I created the thread, I found that the tls segment was difficult to process. Is there a crate here that can quickly create new threads?

**Comment by CtrlZ233** [comment]
This is just a small demo, I'm not sure if this is the right thing to do.
I allocated a tcb object and configured the same cspace and vspace as the root task
```rust
tcb.tcb_configure(ep.cptr(), cnode, CNodeCapData::new(0, 0), vspace, ipc_buffer_addr as u64, ipc_buffer)?;
```
Then I applied for a UserContext and assigned values to the pc register and sp register, but I'm not sure how to assign values to the tp register and gp register, so I assign the corresponding registers of the root task to them.
```rust
let mut user_context = tcb.tcb_read_registers(false, (core::mem::size_of::<UserContext>() / sel4::WORD_SIZE) as u64)?;
*(user_context.pc_mut()) = unsafe { core::mem::transmute(func) };
*(user_context.sp_mut()) = unsafe {
    NEW_STACK.as_ptr().add(4096) as u64
};
let tp: u64;
unsafe {
    asm!("mv {}, tp", out(reg) tp);
}
let gp: u64;
unsafe {
   asm!("mv {}, gp", out(reg) gp);
}
user_context.inner_mut().tp = tp;
user_context.inner_mut().gp = gp;
user_context.inner_mut().a0 = args as u64;
tcb.tcb_write_all_registers(false, &mut user_context)?;
tcb.tcb_set_affinity(1)?;
tcb.tcb_resume()?;
```
When I obtain ipcbuffer and access global variables in a new thread, various exceptions always occur. Is there any problem with the configuration of this thread?

**Comment by nspin** [comment]
I've added [an example](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs) in https://github.com/seL4/rust-sel4/pull/99 that demonstrates a root task that spawns a secondary thread.

Motivated by this issue, I've also redesigned the [`sel4-initialize-tls`](https://sel4.github.io/rust-sel4/views/aarch64-root-task/aarch64-sel4/doc/sel4_initialize_tls/index.html) crate (also in https://github.com/seL4/rust-sel4/pull/99). This crate now exposes an API that encapsulates arch-specific details of TLS region handling to support cases such as the new example and your scenario.

In the new example and in your scenario, the new thread requires an initialized TLS region, along with a pointer to an arch-specific offset into that region in `user_context.inner_mut().tp`. If you are using LLD without a custom linker script, the information needed to initialize a TLS region is embedded into the binary via PHDRS. In the new `spawn-thread` example, this information is gathered via the [`get_tls_image()`](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L215-L231) function. The [`TlsReservation`](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L187-L190) struct uses the [`sel4-initialize-tls`](https://sel4.github.io/rust-sel4/views/aarch64-root-task/aarch64-sel4/doc/sel4_initialize_tls/index.html) crate to allocate a block of memory with the proper size and alignment, initialize it according to the TLS image, and then compute the proper value for the new thread's thread pointer (`.tp`).

The new thread's TLS region is initialized according to the program image, so the thread-local IPC buffer variable will not be set. In the new example, the first thing the new thread does is [set it](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L84) via the `sel4` crate's API.

**Comment by CtrlZ233** [comment]
> I've added [an example](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs) in #99 that demonstrates a root task that spawns a secondary thread.
> 
> Motivated by this issue, I've also redesigned the [`sel4-initialize-tls`](https://sel4.github.io/rust-sel4/views/aarch64-root-task/aarch64-sel4/doc/sel4_initialize_tls/index.html) crate (also in #99). This crate now exposes an API that encapsulates arch-specific details of TLS region handling to support cases such as the new example and your scenario.
> 
> In the new example and in your scenario, the new thread requires an initialized TLS region, along with a pointer to an arch-specific offset into that region in `user_context.inner_mut().tp`. If you are using LLD without a custom linker script, the information needed to initialize a TLS region is embedded into the binary via PHDRS. In the new [`spawn-thread`](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L84) example, this information is gathered via the [`get_tls_image()`](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L215-L231) function. You can, of course, include the TLS image in the binary in a custom linker script, too. The [`TlsReservation`](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L187-L190) struct uses the [`sel4-initialize-tls`](https://sel4.github.io/rust-sel4/views/aarch64-root-task/aarch64-sel4/doc/sel4_initialize_tls/index.html) crate to allocate a block of memory with the proper size and alignment, initialize it according to the TLS image, and then compute the proper value for the new thread's thread pointer (`.tp`).
> 
> The new thread's TLS region is initialized according to the program image, so the thread-local IPC buffer variable will not be set. In the new example, the first thing the new thread does is [set it](https://github.com/seL4/rust-sel4/blob/88e9d4ad95c0da170841ea648caf98de8690ef7a/crates/examples/root-task/spawn-thread/src/main.rs#L84) via the [`sel4` crate's API](https://sel4.github.io/rust-sel4/views/aarch64-root-task/aarch64-sel4/doc/sel4/fn.set_ipc_buffer.html).

OK, got it, thanks.
